-- Ljud-Aragorn v0.35.27 – researched Freesound sound-page candidates.
-- Licenses displayed as CC0 on source pages when reviewed 2026-10-09.
-- Files not downloaded, auditioned or distributed by this migration.
WITH candidates(cue_key,source_url,creator_credit,license_type,license_notes) AS
(VALUES
('ambience.cave','https://freesound.org/people/Rosanajurado/sounds/664051/','Rosanajurado','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 16 s; mörk grottatmosfär, WAV ca 5,4 MB. Sömlös loop kräver bearbetning.'),
('ambience.crypt','https://freesound.org/people/xkeril/sounds/870203/','xkeril','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 80 s; mörkt grottlandskap. WAV 22 MB kräver klippning/komprimering och stämningskontroll.'),
('ambience.door','https://freesound.org/people/Rudmer_Rotteveel/sounds/590947/','Rudmer_Rotteveel','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 1,8 s; långsamt knarrande dörr. Passar övergiven kyrka.'),
('ambience.fire','https://freesound.org/people/forfie/sounds/364992/','forfie','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 36 s; lägerbrasa, WAV ca 4,9 MB. Klipp sömlös loop.'),
('ambience.forest','https://freesound.org/people/EminYILDIRIM/sounds/595875/','EminYILDIRIM','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 21 s; skog nattetid, WAV ca 5,3 MB. Kontrollera loopskarv.'),
('ambience.rain','https://freesound.org/people/Dave_Girtsman/sounds/332496/','Dave_Girtsman','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 37 s MP3; regn på betong. Bygg loop med mjuk övertoning.'),
('ambience.thunder','https://freesound.org/people/alexdarek/sounds/646912/','alexdarek','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 15,5 s; kraftigt åsknedslag. Klipp relevant åskparti.'),
('ambience.water','https://freesound.org/people/nsmusic/sounds/321886/','nsmusic','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 64 s; riktigt vattenfall i Estland. WAV ca 10,8 MB måste komprimeras.'),
('ambience.wind','https://freesound.org/people/bone666138/sounds/520183/','bone666138','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 6 min; vind i träd. Måste redigeras och komprimeras till under 8 MB.'),
('creature.skeleton','https://freesound.org/people/spookymodem/sounds/202102/','spookymodem','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 5,5 s; rasslande skelettben. Klipp till 2–3 korta varianter.'),
('dice.land','https://freesound.org/people/Christopherderp/sounds/342202/','Christopherderp','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 1,0 s; tärning mot trä. Klipp ut sista nedslaget till separat landningsljud.'),
('dice.roll','https://freesound.org/people/Flem0527/sounds/629982/','Flem0527','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 1,1 s; två tärningar mot träbord. Kort färdig effekt.'),
('event.footsteps','https://freesound.org/people/Fission9/sounds/521588/','Fission9','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 2,7 s; fyra grusfotsteg. Dela till separata steg för återanvändning.'),
('magic.fire','https://freesound.org/people/Za-Games/sounds/539972/','Za-Games','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 0,8 s; snabb flamstöt. Kontrollera att ljudet matchar eldklotets animation.'),
('melee.fumble','https://freesound.org/people/Christopherderp/sounds/342452/','Christopherderp','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 0,5 s; svärd som tappas. Klar kort effekt.'),
('melee.hit','https://freesound.org/people/Christopherderp/sounds/342397/','Christopherderp','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 2,5 s; svärdssving med metallisk träff. Klipp ut anslaget och provlyssna.'),
('melee.parry','https://freesound.org/people/Christopherderp/sounds/364531/','Christopherderp','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 2,1 s; producerad svärdskollision. Skär ned efterklang för parering.'),
('melee.swing','https://freesound.org/people/GrayEpic/sounds/782966/','GrayEpic','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 3,2 s; svärdssving med träff. Isolera svingdelen för denna händelse.'),
('ranged.bow_release','https://freesound.org/people/Ali_6868/sounds/384915/','Ali_6868','CC0 1.0 (enligt Freesound)','Webbgranskning 2026-10-09: Ljudsidan anger Creative Commons Zero (CC0), men ljudet är inte nedladdat eller genomlyssnat. 0,8 s; inspelad pilbågssträng vid skott.')
)
UPDATE public.rule_sound_cues AS cues SET source_url=c.source_url,
 creator_credit=c.creator_credit,license_type=c.license_type,
 license_notes=c.license_notes,source_status='shortlisted'
FROM candidates c WHERE cues.cue_key=c.cue_key AND cues.asset_path IS NULL AND cues.source_url IS NULL;
