-- v0.35.40 · seedade droger, gifter och växter från användarens uppladdade Expert-regelsidor.
-- Okända priser är 0 + metadata.price_pending=true och FÅR INTE säljas innan SL sätter pris.
-- RLS och adminspärrar återanvänder public.rule_shop_items.
INSERT INTO public.rule_shop_items
(item_key,category,name,description,price_amount,price_currency,purchase_kind,quantity_per_purchase,source_key,sort_order,metadata,active)
VALUES
('alchemy_celli','Trolldrycker','Celli','Läker 1 KP varannan timme under verkningstiden.',400,'SM','equipment',1,'expert_magibok_s38_40_user',7000,'{"form":"Vitt pulver","kind":"dryck","onset":"1 timme","skill":"Drogkunskap, Läkedrogskunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"1T8+10 timmar","price_note":"Pris enligt handskriven notering i användarens underlag","consumption":"Blandas med vatten och dricks","ingredients":"Svanblommelök och blad av korsört.","after_effect":"","price_pending":false,"after_duration":""}'::jsonb,true),
('alchemy_duragos','Trolldrycker','Duragos','Motverkar och botar sårinfektioner.',0,'SM','equipment',1,'expert_magibok_s38_40_user',7010,'{"form":"Salva","kind":"dryck","onset":"","skill":"Drogkunskap, Läkedrogskunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"1 dygn","price_note":"","consumption":"Smörjes på såret","ingredients":"23 g korsörtsrot.","after_effect":"","price_pending":true,"after_duration":""}'::jsonb,true),
('alchemy_liliansblad','Trolldrycker','Liliansblad','Förbättrar hård fysisk ansträngning kraftigt under effekten.',295,'SM','equipment',1,'expert_magibok_s38_40_user',7020,'{"form":"Blad i gelé","kind":"dryck","onset":"1T10 minuter","skill":"Drogkunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"1T4+11 timmar","price_note":"Pris enligt handskriven notering i användarens underlag","consumption":"Tuggas","ingredients":"Blad av liliansört och korsörtsblad.","after_effect":"Darrighet; SMI-baserade färdigheter halveras.","price_pending":false,"after_duration":"2T4 timmar"}'::jsonb,true),
('alchemy_karsonolja','Trolldrycker','Karsonolja','Förbättrar köldtålighet ned till ungefär −30 °C; gör brukaren starkt illaluktande och lätt att upptäcka för luktsinne.',0,'SM','equipment',1,'expert_magibok_s38_40_user',7030,'{"form":"Olja","kind":"dryck","onset":"0","skill":"Drogkunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"1T4+20 timmar","price_note":"","consumption":"Smörjes på kroppen","ingredients":"Utvinning ur karsonens fett.","after_effect":"","price_pending":true,"after_duration":""}'::jsonb,true),
('alchemy_svartblod','Gifter','Svartblod','Skadar den förgiftade enligt reglerna för grundgift.',0,'SM','equipment',1,'expert_magibok_s38_40_user',7040,'{"form":"Trögflytande svart vätska","kind":"gift","onset":"1T4 stridsrundor","skill":"Drogkunskap, Giftkunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"Se grundgift","price_note":"","consumption":"I mat eller dryck, eller på vapen","ingredients":"Magvätska från flygödla och krossade matikoratänder.","after_effect":"","price_pending":true,"after_duration":""}'::jsonb,true),
('alchemy_ganas','Trolldrycker','Ganas','En dos räknas som en dagsranson mat.',80,'SM','equipment',1,'expert_magibok_s38_40_user',7050,'{"form":"Hård brödkaka","kind":"dryck","onset":"","skill":"Drogkunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"1 dygn","price_note":"Pris enligt handskriven notering i användarens underlag","consumption":"Äts","ingredients":"Mjöl av gyllensäd samt vanliga ingredienser för bakning.","after_effect":"","price_pending":false,"after_duration":""}'::jsonb,true),
('alchemy_sarrassos','Trolldrycker','Sarrassos','Sinnen skärps; +5 på uppfattningsfärdigheter. Starka sinnesintryck kan kräva svårt PSY-slag.',0,'SM','equipment',1,'expert_magibok_s38_40_user',7060,'{"form":"Pulver","kind":"dryck","onset":"1T6 stridsrundor","skill":"Drogkunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"1T10+10 minuter","price_note":"","consumption":"Inhaleras","ingredients":"Pollen av purpursippa.","after_effect":"Darrighet; SMI-baserade färdigheter halveras.","price_pending":true,"after_duration":"1T10+10 minuter"}'::jsonb,true),
('alchemy_stjarnedryck','Trolldrycker','Stjärnedryck','Tankeförmågan skärps; INT ökar med 1T4 poäng.',435,'SM','equipment',1,'expert_magibok_s38_40_user',7070,'{"form":"Vätska","kind":"dryck","onset":"2T4 minuter","skill":"Drogkunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"1T20+60 minuter","price_note":"Pris enligt handskriven notering i användarens underlag","consumption":"Dricks","ingredients":"Davidsblomma och tårbuskbär.","after_effect":"Brukaren somnar när effekten klingar av.","price_pending":false,"after_duration":"1T20+120 minuter"}'::jsonb,true),
('alchemy_stridsdryck','Trolldrycker','Stridsdryck','STY +1T6, SMI +1T4 och motsvarande höjning av berörda färdigheter; förflyttning +2.',0,'SM','equipment',1,'expert_magibok_s38_40_user',7080,'{"form":"Vätska","kind":"dryck","onset":"1T6 minuter","skill":"Drogkunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"1T4+15 minuter","price_note":"","consumption":"Dricks","ingredients":"Tänder från en kimeras lejonhuvud.","after_effect":"Darrighet och slöhet; förflyttning, INT, SMI och relaterade färdigheter halveras.","price_pending":true,"after_duration":"1T6+20 minuter"}'::jsonb,true),
('alchemy_erisinon','Gifter','Erisinon','Framkallar våldsamma hallucinationer; verkningstiden kan halveras vid lyckat giftslag.',350,'SM','equipment',1,'expert_magibok_s38_40_user',7090,'{"form":"Grönt pulver","kind":"gift","onset":"1T3 minuter","skill":"Drogkunskap, Giftkunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"1T10+10 minuter","price_note":"Pris enligt handskriven notering i användarens underlag","consumption":"Blandas med vatten och dricks","ingredients":"Frukter från gyllenbuske.","after_effect":"","price_pending":false,"after_duration":""}'::jsonb,true),
('alchemy_smaugifonia','Trolldrycker','Smaugifonia','Häver gradvis kramper, skräck- och ångesttillstånd, även magiskt skapade.',0,'SM','equipment',1,'expert_magibok_s38_40_user',7100,'{"form":"Dryck","kind":"dryck","onset":"1T3 minuter","skill":"Drogkunskap, Läkedrogskunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"1T4 minuter","price_note":"","consumption":"Dricks","ingredients":"Drakbär.","after_effect":"Brukaren somnar efter att effekten upphör och vaknar återställd.","price_pending":true,"after_duration":"1T4+3 timmar"}'::jsonb,true),
('alchemy_rekupera','Gifter','Rekupera','Framkallar djup sömn; giftslag kan förkorta verkan.',600,'SM','equipment',1,'expert_magibok_s38_40_user',7110,'{"form":"Blått pulver","kind":"gift","onset":"1T6 minuter","skill":"Drogkunskap, Läkedrogskunskap, Giftkunskap","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"duration":"1T6+6 timmar","price_note":"Pris enligt handskriven notering i användarens underlag","consumption":"Blandas med mat eller dryck","ingredients":"Drakbär och korsörtsblad.","after_effect":"Huvudvärk och slöhet; SMI, INT och färdigheter knutna till dem sänks.","price_pending":false,"after_duration":"1T4 timmar"}'::jsonb,true),
('alchemy_draktrad','Växter','Drakträd','Träd · Sällsynt · Torra bergssluttningar',0,'SM','equipment',1,'expert_magibok_s40_41_user',8000,'{"kind":"växt","type":"Träd","parts":"Bär","fruits":"Stora lingonlika, söta bär","rarity":"Sällsynt","season":"Högsommar","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"climate":"Tempererad","habitat":"Torra bergssluttningar","appearance":"Mörkt purpurfärgade blad; blå blommor","price_pending":true}'::jsonb,true),
('alchemy_svanblomma','Växter','Svanblomma','Ört · Vanlig · Fält och ängar',0,'SM','equipment',1,'expert_magibok_s40_41_user',8010,'{"kind":"växt","type":"Ört","parts":"Rotlök","fruits":"Lileliknande blomning","rarity":"Vanlig","season":"Sen vår","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"climate":"Subtropisk","habitat":"Fält och ängar","appearance":"Gröna löv, vita blommor","price_pending":true}'::jsonb,true),
('alchemy_korsort','Växter','Korsört','Ört · Vanlig · Sumpmarker',0,'SM','equipment',1,'expert_magibok_s40_41_user',8020,'{"kind":"växt","type":"Ört","parts":"Blad och rot","fruits":"","rarity":"Vanlig","season":"Sommar","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"climate":"Subarktisk","habitat":"Sumpmarker","appearance":"Korsformade blad, röda blommor","price_pending":true}'::jsonb,true),
('alchemy_liliansort','Växter','Liliansört','Ört · Sällsynt · Pinjeskogar',0,'SM','equipment',1,'expert_magibok_s40_41_user',8030,'{"kind":"växt","type":"Ört","parts":"Blad","fruits":"","rarity":"Sällsynt","season":"Tidig vår","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"climate":"Subtropisk","habitat":"Pinjeskogar","appearance":"Tulpanformade gulgröna blommor","price_pending":true}'::jsonb,true),
('alchemy_davidsblomma','Växter','Davidsblomma','Ört · Ovanlig · Havsstränder',0,'SM','equipment',1,'expert_magibok_s40_41_user',8040,'{"kind":"växt","type":"Ört","parts":"Blad och blomma","fruits":"","rarity":"Ovanlig","season":"","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"climate":"Tempererad","habitat":"Havsstränder","appearance":"","price_pending":true}'::jsonb,true),
('alchemy_tarbuske','Växter','Tårbuske','Buske · Ovanlig · Sandiga skogar',0,'SM','equipment',1,'expert_magibok_s40_41_user',8050,'{"kind":"växt","type":"Buske","parts":"Bär","fruits":"Körsbärsliknande bär","rarity":"Ovanlig","season":"Sensommar","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"climate":"Tempererad","habitat":"Sandiga skogar","appearance":"Ljusblå blommor; rundbladig","price_pending":true}'::jsonb,true),
('alchemy_gyllenbuske','Växter','Gyllenbuske','Buske · Mycket sällsynt · Öppna skogar',0,'SM','equipment',1,'expert_magibok_s40_41_user',8060,'{"kind":"växt","type":"Buske","parts":"Bär","fruits":"Hallonlika orange bär","rarity":"Mycket sällsynt","season":"Sensommar","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"climate":"Tempererad och subtropisk","habitat":"Öppna skogar","appearance":"Små gröna blommor; gula barr","price_pending":true}'::jsonb,true),
('alchemy_gyllensad','Växter','Gyllensäd','Sädesgräs · Mycket sällsynt · Fält och ängar',0,'SM','equipment',1,'expert_magibok_s40_41_user',8070,'{"kind":"växt","type":"Sädesgräs","parts":"Ax","fruits":"Gyllengult sädesax","rarity":"Mycket sällsynt","season":"Höst","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"climate":"Tempererad","habitat":"Fält och ängar","appearance":"Odlas även av skogsfolk","price_pending":true}'::jsonb,true),
('alchemy_purpursippa','Växter','Purpursippa','Ört · Mycket sällsynt · Å- och bäckstränder',0,'SM','equipment',1,'expert_magibok_s40_41_user',8080,'{"kind":"växt","type":"Ört","parts":"Pollen","fruits":"","rarity":"Mycket sällsynt","season":"Sen vår","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"climate":"Subarktisk","habitat":"Å- och bäckstränder","appearance":"Purpurfärgade blommor, långsmala blad","price_pending":true}'::jsonb,true),
('alchemy_svartblister','Växter','Svartblister','Ört · Sällsynt · Sjöstränder',0,'SM','equipment',1,'expert_magibok_s40_41_user',8090,'{"kind":"växt","type":"Ört","parts":"Rot","fruits":"","rarity":"Sällsynt","season":"Högsommar","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"climate":"Arktisk","habitat":"Sjöstränder","appearance":"Blå maskroslika blommor; mycket mörka löv","price_pending":true}'::jsonb,true),
('alchemy_galgort','Växter','Galgört','Ört · Mycket sällsynt · Tidigare avrättningsplatser',0,'SM','equipment',1,'expert_magibok_s40_41_user',8100,'{"kind":"växt","type":"Ört","parts":"Blad","fruits":"","rarity":"Mycket sällsynt","season":"Högsommar","source":"Expert – Droger & växter (uppladdade sidor)","alchemy":true,"climate":"Tempererad","habitat":"Tidigare avrättningsplatser","appearance":"Vinröda rosblommor; runda blad","price_pending":true}'::jsonb,true)
ON CONFLICT (item_key) DO NOTHING;
