-- HAJ: persistent hex/area effects; explicit event damage values, not invented Expert spell scaling.
CREATE TABLE IF NOT EXISTS public.combat_area_effects(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 combat_id uuid NOT NULL REFERENCES public.combat_instances(id) ON DELETE CASCADE,
 campaign_id uuid NOT NULL REFERENCES public.campaigns(id) ON DELETE CASCADE,
 effect_id uuid NOT NULL REFERENCES public.rule_effects(id),
 source_combatant_id uuid REFERENCES public.combatants(id) ON DELETE SET NULL,
 center_q integer NOT NULL,center_r integer NOT NULL,
 radius integer NOT NULL DEFAULT 0 CHECK(radius BETWEEN 0 AND 15),
 applied_round integer NOT NULL CHECK(applied_round>=1),
 expires_round integer CHECK(expires_round IS NULL OR expires_round>=applied_round),
 status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','expired','removed')),
 parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS combat_area_effects_combat_idx ON public.combat_area_effects(combat_id,status);
ALTER TABLE public.combat_area_effects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS combat_area_effects_read ON public.combat_area_effects;
CREATE POLICY combat_area_effects_read ON public.combat_area_effects FOR SELECT TO authenticated
 USING (private.is_admin() OR private.is_campaign_member(campaign_id));
DROP POLICY IF EXISTS combat_area_effects_write ON public.combat_area_effects;
CREATE POLICY combat_area_effects_write ON public.combat_area_effects FOR ALL TO authenticated
 USING (private.is_admin() OR private.is_campaign_gm(campaign_id))
 WITH CHECK (private.is_admin() OR private.is_campaign_gm(campaign_id));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.combat_area_effects TO authenticated;

CREATE TABLE IF NOT EXISTS public.combat_area_events(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 area_id uuid NOT NULL REFERENCES public.combat_area_effects(id) ON DELETE CASCADE,
 combat_id uuid NOT NULL REFERENCES public.combat_instances(id) ON DELETE CASCADE,
 campaign_id uuid NOT NULL REFERENCES public.campaigns(id) ON DELETE CASCADE,
 combatant_id uuid NOT NULL REFERENCES public.combatants(id) ON DELETE CASCADE,
 round_number integer NOT NULL CHECK(round_number>=1),
 event_type text NOT NULL CHECK(event_type IN ('enter','stay','exit')),
 gross_damage integer NOT NULL DEFAULT 0 CHECK(gross_damage>=0),
 protection integer NOT NULL DEFAULT 0 CHECK(protection>=0),
 net_damage integer NOT NULL DEFAULT 0 CHECK(net_damage>=0),
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS combat_area_events_lookup ON public.combat_area_events(combat_id,round_number);
CREATE UNIQUE INDEX IF NOT EXISTS combat_area_stay_once ON public.combat_area_events(area_id,combatant_id,round_number) WHERE event_type='stay';
ALTER TABLE public.combat_area_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS combat_area_events_read ON public.combat_area_events;
CREATE POLICY combat_area_events_read ON public.combat_area_events FOR SELECT TO authenticated
 USING (private.is_admin() OR private.is_campaign_member(campaign_id));
DROP POLICY IF EXISTS combat_area_events_write ON public.combat_area_events;
CREATE POLICY combat_area_events_write ON public.combat_area_events FOR ALL TO authenticated
 USING (private.is_admin() OR private.is_campaign_gm(campaign_id))
 WITH CHECK (private.is_admin() OR private.is_campaign_gm(campaign_id));
GRANT SELECT ON public.combat_area_events TO authenticated;

INSERT INTO public.rule_effects
 (code,name,description,polarity,category,target_type,duration_unit,default_duration_rounds,expiration_condition,stacking,modifiers,parameter_schema,active)
VALUES
 ('area_fire','ELDOMRÅDE','Skadeområde på hex. SL anger eventuell skada vid inträde, vistelse eller utträde.','negative','environment','area','round',null,'manual','refresh','{"type":"area_damage","damage_kind":"fire"}','{"damage_on_enter":"integer","damage_on_stay":"integer","damage_on_exit":"integer"}',true),
 ('area_poison','GIFTMOLN','Giftområde på hex. SL anger skadevärden och varaktighet.','negative','environment','area','round',null,'manual','refresh','{"type":"area_damage","damage_kind":"poison"}','{"damage_on_enter":"integer","damage_on_stay":"integer","damage_on_exit":"integer"}',true),
 ('area_fog','DIMMA','Områdesbaserad skymmande sikt. Ingen automatisk skadeberäkning.','neutral','environment','area','round',null,'manual','refresh','{"type":"area_terrain","sight_mode":"obscuring"}','{}',true),
 ('area_difficult','SVÅR TERRÄNG','Områdesbaserad svår terräng med dubblerad förflyttningskostnad för markbundna.','negative','environment','area','round',null,'manual','refresh','{"type":"area_terrain","movement_mode":"difficult"}','{}',true)
ON CONFLICT (code) DO NOTHING;
