-- Gandalf v0.35.26 – requirements only, no audio recordings included.
ALTER TABLE public.rule_sound_cues
 ADD COLUMN IF NOT EXISTS priority smallint NOT NULL DEFAULT 2 CHECK (priority BETWEEN 1 AND 3),
 ADD COLUMN IF NOT EXISTS sound_kind text NOT NULL DEFAULT 'oneshot' CHECK (sound_kind IN ('loop','oneshot')),
 ADD COLUMN IF NOT EXISTS usage_hint text NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS search_terms text NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS target_variants smallint NOT NULL DEFAULT 1 CHECK (target_variants BETWEEN 1 AND 8),
 ADD COLUMN IF NOT EXISTS integration_status text NOT NULL DEFAULT 'planned' CHECK (integration_status IN ('connected','planned')),
 ADD COLUMN IF NOT EXISTS source_status text NOT NULL DEFAULT 'needed' CHECK (source_status IN ('needed','shortlisted','verified')),
 ADD COLUMN IF NOT EXISTS source_url text,
 ADD COLUMN IF NOT EXISTS creator_credit text,
 ADD COLUMN IF NOT EXISTS license_type text,
 ADD COLUMN IF NOT EXISTS license_notes text;
INSERT INTO public.rule_sound_cues(cue_key,title,category,volume,enabled) VALUES
('ambience.church','Övergiven kyrka','ambience',0.65,true),
('ambience.village','Övergiven by','ambience',0.65,true),
('creature.dragon','Drake ryter','creature',0.65,true),
('creature.horse','Häst frustar','creature',0.65,true),
('creature.salamander','Eldsalamander','creature',0.65,true),
('creature.skeleton','Skelettvakt rasslar','creature',0.65,true),
('creature.wolf','Varg morrar','creature',0.65,true),
('creature.zombie','Odöd stönar','creature',0.65,true),
('event.chain','Kedjor skramlar','event',0.65,true),
('event.footsteps','Fotsteg på sten','event',0.65,true),
('event.lock','Lås vrids','event',0.65,true),
('event.stone','Sten rasar','event',0.65,true),
('event.whisper','Viskningar i mörkret','event',0.65,true),
('magic.ice','Frostmagi','magic',0.65,true),
('magic.lightning','Blixtmagi','magic',0.65,true),
('magic.shield','Magisk barriär','magic',0.65,true),
('magic.summon','Frammaning','magic',0.65,true),
('melee.blade','Svärdshugg med egg','melee',0.65,true),
('melee.blunt','Trubbig vapenträff','melee',0.65,true),
('melee.shield','Slag mot sköld','melee',0.65,true),
('ranged.arrow_hit','Pil träffar','ranged',0.65,true),
('ranged.bow_draw','Pilbåge spänns','ranged',0.65,true),
('ranged.bow_release','Pil avfyras','ranged',0.65,true),
('ranged.crossbow','Armborst avfyras','ranged',0.65,true),
('ranged.sling','Slunga och sten','ranged',0.65,true)
ON CONFLICT(cue_key) DO NOTHING;
WITH inventory(cue_key,priority,sound_kind,usage_hint,search_terms,target_variants,integration_status) AS
( VALUES
('ambience.battle',2,'oneshot','Stridsmuller för SL','battle rumble swords distant',2,'connected'),
('ambience.cave',1,'loop','Grotta och underjordisk gång','cave ambience dripping echo loop',2,'connected'),
('ambience.church',1,'loop','Kyrkobyggnadens inre','abandoned church creak reverb ambience loop',2,'planned'),
('ambience.crypt',1,'loop','Kyrka gravkapell och krypta','haunted church crypt stone ambience loop',2,'connected'),
('ambience.door',2,'oneshot','Trädörr öppnas eller stängs','creaking wooden door medieval',3,'connected'),
('ambience.fire',2,'loop','Brasa vid läger','campfire crackle fire ambience loop',2,'connected'),
('ambience.forest',1,'loop','Skog nattetid och gravplats','forest night wind owl ambience loop',2,'connected'),
('ambience.ghost',1,'oneshot','Osaliga andar manifesterar sig','ghost eerie whisper supernatural',3,'connected'),
('ambience.night',2,'loop','Nattvind i Skelettbyn','night wind eerie atmosphere loop',2,'connected'),
('ambience.rain',1,'loop','Regn under nattlägret','rain steady forest ambience loop',2,'connected'),
('ambience.ruins',1,'loop','Kvarnruinen och övergivna hus','abandoned village ruins dark ambience loop',2,'connected'),
('ambience.tavern',2,'loop','Värdshusmiljö','medieval tavern crowd ambience loop',2,'connected'),
('ambience.thunder',1,'oneshot','Åskslag under oväder','thunderclap storm distant thunder',3,'connected'),
('ambience.village',1,'loop','Skelettbyns tomma hus och bygator','abandoned village eerie ambience loop',2,'planned'),
('ambience.water',2,'loop','Bäck och vattenfall','waterfall flowing river ambience loop',2,'connected'),
('ambience.wind',2,'loop','Blåst utomhus','wind blowing trees ambience loop',2,'connected'),
('creature.dragon',3,'oneshot','Stort vidunder','dragon roar monster growl',2,'planned'),
('creature.horse',2,'oneshot','Häst och ryttare','horse neigh snort hooves',3,'planned'),
('creature.salamander',2,'oneshot','Frammanad eldsalamander','small fire elemental crackling hiss',3,'planned'),
('creature.skeleton',1,'oneshot','Skelettvakt rör sig','skeleton bones rattle footsteps',3,'planned'),
('creature.wolf',2,'oneshot','Varg hotar eller närmar sig','wolf growl snarl howl',3,'planned'),
('creature.zombie',2,'oneshot','Odöd fiende närmar sig','undead groan zombie breath',3,'planned'),
('dice.land',1,'oneshot','Tärningarna landar och resultat visas','dice settling clack wood',3,'connected'),
('dice.roll',1,'oneshot','Tärningsslag inleds','dice rolling wooden bowl tabletop',3,'connected'),
('event.chain',2,'oneshot','Bojor och kedjor','chains rattling dragging metal',3,'planned'),
('event.footsteps',1,'oneshot','Steg i ruin och kyrka','boots footsteps gravel stone',4,'planned'),
('event.lock',3,'oneshot','Nyckel vrids i lås','old lock key turning',2,'planned'),
('event.stone',2,'oneshot','Rasande ruiner och sten','stone rubble rocks collapsing',3,'planned'),
('event.whisper',1,'oneshot','Osaliga andar i Skelettbyn','ghost whispers eerie distant voices',3,'planned'),
('magic.antimagic',2,'oneshot','Antimagi stoppar besvärjelse','magic barrier dispel anti magic',3,'connected'),
('magic.cast',1,'oneshot','En besvärjelse kastas','spell cast arcane whoosh',3,'connected'),
('magic.fail',1,'oneshot','Besvärjelse misslyckas','magic fizzle failed spell',3,'connected'),
('magic.fire',1,'oneshot','Eldklot och eldmagiska effekter','fireball blast magic fire',4,'connected'),
('magic.heal',1,'oneshot','Helning eller återhämtning','healing spell shimmer',3,'connected'),
('magic.ice',2,'oneshot','Isbesvärjelse används','ice spell freeze crackle magic',3,'planned'),
('magic.lightning',2,'oneshot','Blixtbesvärjelse träffar','lightning bolt electricity magic blast',3,'planned'),
('magic.shield',2,'oneshot','Beskyddare eller magiskt skydd','magic shield protective barrier hum',3,'planned'),
('magic.success',2,'oneshot','Besvärjelse lyckas','magic sparkle chime success',3,'connected'),
('magic.summon',2,'oneshot','Varelse frammanas','summoning portal magical swirl',3,'planned'),
('melee.blade',2,'oneshot','Särskild träff med skärande vapen','blade slash cut sword impact',3,'planned'),
('melee.blunt',2,'oneshot','Klubba eller hammare träffar','mace hammer thud blunt impact',3,'planned'),
('melee.fumble',2,'oneshot','Fummel i strid','weapon drop clatter fumble',2,'connected'),
('melee.hit',1,'oneshot','Närstrid gör skada','sword impact metal flesh',4,'connected'),
('melee.miss',1,'oneshot','Attack missar','sword swing miss whoosh',3,'connected'),
('melee.parry',1,'oneshot','Parering med vapen eller sköld','sword clash metal parry',4,'connected'),
('melee.shield',1,'oneshot','Vapen träffar sköld','sword hit wooden shield clash',4,'planned'),
('melee.swing',1,'oneshot','Närstridsattack inleds','sword whoosh sword swing steel',4,'connected'),
('ranged.arrow_hit',1,'oneshot','Pil träffar mål','arrow impact shield wood flesh',4,'planned'),
('ranged.bow_draw',1,'oneshot','Pilbåge förbereder skottet','bow string drawing leather creak',3,'planned'),
('ranged.bow_release',1,'oneshot','Pil lämnar pilbågen','bow twang arrow release',4,'planned'),
('ranged.crossbow',2,'oneshot','Skäkta avfyras från armborst','crossbow shoot bolt twang',3,'planned'),
('ranged.sling',2,'oneshot','Sten skjuts från slunga','sling stone whip release',3,'planned')
)
UPDATE public.rule_sound_cues AS c SET priority=i.priority::smallint,sound_kind=i.sound_kind,
 usage_hint=i.usage_hint,search_terms=i.search_terms,target_variants=i.target_variants::smallint,
 integration_status=i.integration_status FROM inventory i WHERE c.cue_key=i.cue_key;
